        <div id="logo">
        	<img src="<?php echo $this->basePath()?>/site/imagens/logotransp.png" height="100%">
        </div>
        <div id="texto">
        Catálogo<br>Online para<br>Auto Peças
        </div> 
        
        <div id="login">
        	<form class="form-inline" >
        		<label for="usuario">Usuário</label><br /> 
		 		<input type="text" name="usuario" class="form-control" style="width: 100%" ><br /><br />
		 		
        		<label for="senha">Senha</label><br /> 
		 		<input type="password" name="senha" class="form-control" style="width: 100%" ><br />
		 		<br />
		 		
		 		<button type="button" class="btn btn-success" id="btnsalvar" style="float: right;">Entrar</button>
		 		<div id="resultado" style="color: #f00"></div>
        	</form>
        </div>